// Statuses 
export const FILTER_PANEL_STATUS = 'FILTER_PANEL'
export const PRODUCT_DETILE_STATUS = 'PRODUCT_DETILE_STATUS'
export const LIVE_CHAT_STATUS = 'LIVE_CHAT_STATUS'

// memories
export const PRODUCT_MEMORY = 'PRODUCT_MEMORY'
export const CATEGORY_MEMORY = 'CATEGORY_MEMORY'
export const PRODUCT_DETIlE_PAYLOAD = 'PRODUCT_DETIlE_PAYLOAD'
export const PRODUCT_SORTED = 'PRODUCT_SORTED'
export const CART_MEMORY = 'CART_MEMORY'
export const WISHLIST_MEMORY = 'WISHLIST_MEMORY'